// Package narrate is the OPTIONAL narrative layer. It is deliberately OUTSIDE the
// detection/correlation core (which stays deterministic and LLM-free) — it only
// turns an already-built investigation into readable text.
//
// Threat model: every telemetry string (command lines, file names, addresses) is
// attacker-controlled and hostile — an indirect prompt-injection surface. The
// defenses here are STRUCTURAL, not string-matching:
//
//   - Instruction/data separation: a Model may only choose an allow-listed
//     statement Kind and cite grounding event ids. It never supplies output text.
//   - Rendering from trusted data: sentence text is generated by THIS package
//     from the looked-up event/score data, so attacker bytes are rendered as
//     inert, delimited data — never as instructions and never verbatim from the
//     richest vector (command lines are not rendered at all).
//   - Allow-listed verdict: the risk wording derives from the trusted numeric
//     score, so a compromised Model cannot assert "benign".
//   - Grounding enforcement: every emitted sentence must cite >=1 real event id
//     of the matching type; unattributed or mistyped statements are rejected.
//
// See narrate_test.go for the red-team suite that plants injection payloads and
// asserts the narrator neither obeys them nor drops grounding.
package narrate

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"sentinelx/backend/correlate"
	"sentinelx/backend/store"
)

// EventView is the trusted, structured projection of an event the narrator
// renders from.
type EventView struct {
	ID     string
	Type   string
	Image  string
	Object string
	Verb   string
	TS     time.Time
}

// DetectionView is the trusted projection of a detection.
type DetectionView struct {
	RuleID    string
	Technique []string
	EventIDs  []string
}

// InvestigationView is the grounded input to a Model. Risk and Techniques come
// from the trusted deterministic core, not from any model.
type InvestigationView struct {
	ID             int64
	Risk           int
	Techniques     []string
	DetectionCount int
	Events         []EventView
	Detections     []DetectionView // optional richer grounding for a real-LLM Model
}

// StmtKind is an allow-listed statement shape.
type StmtKind string

const (
	KindExec StmtKind = "exec"
	KindNet  StmtKind = "net"
	KindFile StmtKind = "file"
	KindDNS  StmtKind = "dns"
	KindRisk StmtKind = "risk"
)

var kindEventType = map[StmtKind]string{
	KindExec: "process_start",
	KindNet:  "net_connect",
	KindFile: "file_write",
	KindDNS:  "dns_query",
}

// Statement is all a Model controls: a shape and which grounded events to cite.
type Statement struct {
	Kind     StmtKind
	EventIDs []string
}

// Model drafts statements. A real LLM implements this behind the same interface;
// its raw text output would be mapped to (Kind, EventIDs) and is subject to every
// guard below — it can never inject free text into the narrative.
type Model interface {
	Draft(InvestigationView) []Statement
}

// Sentence is a rendered, grounded output line.
type Sentence struct {
	Text     string   `json:"text"`
	EventIDs []string `json:"event_ids"`
}

// Narrative is the guarded output.
type Narrative struct {
	Sentences []Sentence `json:"sentences"`
	Rejected  int        `json:"rejected"`
}

// Text joins the sentences.
func (n Narrative) Text() string {
	parts := make([]string, len(n.Sentences))
	for i, s := range n.Sentences {
		parts[i] = s.Text
	}
	return strings.Join(parts, " ")
}

// Narrator applies the guard layer around a Model.
type Narrator struct{ Model Model }

// New returns a Narrator; if m is nil the deterministic GroundedModel is used.
func New(m Model) *Narrator {
	if m == nil {
		m = GroundedModel{}
	}
	return &Narrator{Model: m}
}

// Render produces a grounded narrative, rejecting any statement that is
// unattributed, mistyped, or outside the allow-list.
func (nr *Narrator) Render(view InvestigationView) Narrative {
	grounding := make(map[string]EventView, len(view.Events))
	for _, e := range view.Events {
		grounding[e.ID] = e
	}
	var out Narrative
	for _, st := range nr.Model.Draft(view) {
		text, ok := nr.renderStatement(st, view, grounding)
		if !ok {
			out.Rejected++
			continue
		}
		out.Sentences = append(out.Sentences, Sentence{Text: text, EventIDs: st.EventIDs})
	}
	return out
}

func (nr *Narrator) renderStatement(st Statement, view InvestigationView, grounding map[string]EventView) (string, bool) {
	if len(st.EventIDs) == 0 {
		return "", false // unattributed
	}
	// Risk verdict is rendered from the trusted score; the Model cannot word it.
	if st.Kind == KindRisk {
		for _, id := range st.EventIDs {
			if _, ok := grounding[id]; !ok {
				return "", false
			}
		}
		tech := "no mapped techniques"
		if len(view.Techniques) > 0 {
			tech = strings.Join(view.Techniques, ", ")
		}
		return fmt.Sprintf("This %s investigation fired %d detections spanning %s (risk %d/100).",
			verdict(view.Risk), view.DetectionCount, tech, view.Risk), true
	}
	wantType, ok := kindEventType[st.Kind]
	if !ok {
		return "", false // not on the allow-list
	}
	ev, ok := grounding[st.EventIDs[0]]
	if !ok || ev.Type != wantType {
		return "", false // ungrounded or mistyped (a benign event cited under a scary kind)
	}
	img := san(ev.Image)
	switch st.Kind {
	case KindExec:
		return fmt.Sprintf("Process %s executed.", img), true
	case KindNet:
		return fmt.Sprintf("%s connected to %s.", img, san(ev.Object)), true
	case KindFile:
		return fmt.Sprintf("%s %s %s.", img, verbOr(ev.Verb, "wrote"), san(ev.Object)), true
	case KindDNS:
		return fmt.Sprintf("%s resolved %s.", img, san(ev.Object)), true
	}
	return "", false
}

func verdict(risk int) string {
	switch {
	case risk >= 80:
		return "high-risk"
	case risk >= 50:
		return "elevated-risk"
	default:
		return "low-risk"
	}
}

func verbOr(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

// san renders an untrusted string as inert data: strip control characters and
// newlines, collapse whitespace, and cap length. Command lines are never
// rendered at all (they are the richest injection vector).
func san(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			b.WriteByte(' ')
			continue
		}
		b.WriteRune(r)
	}
	out := strings.Join(strings.Fields(b.String()), " ")
	if len(out) > 120 {
		out = out[:117] + "..."
	}
	if out == "" {
		return "(unknown)"
	}
	return out
}

// GroundedModel is the deterministic shipping Model: one statement per grounded
// event plus a risk summary. Safe by construction — it never emits text.
type GroundedModel struct{}

// Draft implements Model.
func (GroundedModel) Draft(view InvestigationView) []Statement {
	evs := append([]EventView(nil), view.Events...)
	sort.Slice(evs, func(i, j int) bool { return evs[i].TS.Before(evs[j].TS) })
	var out []Statement
	for _, e := range evs {
		var k StmtKind
		switch e.Type {
		case "process_start":
			k = KindExec
		case "net_connect":
			k = KindNet
		case "file_write", "file_read":
			k = KindFile
		case "dns_query":
			k = KindDNS
		default:
			continue
		}
		out = append(out, Statement{Kind: k, EventIDs: []string{e.ID}})
	}
	// Risk summary grounded on the investigation's events.
	if len(evs) > 0 {
		ids := make([]string, len(evs))
		for i, e := range evs {
			ids[i] = e.ID
		}
		out = append(out, Statement{Kind: KindRisk, EventIDs: ids})
	}
	return out
}

// ViewFrom builds a trusted InvestigationView from an investigation and the
// event store.
func ViewFrom(inv *correlate.Investigation, events store.EventStore) InvestigationView {
	v := InvestigationView{ID: inv.ID, Risk: inv.RiskScore, Techniques: inv.TechniqueSet, DetectionCount: len(inv.Detections)}
	for id := range inv.EventIDs {
		ev, ok := events.Get(id)
		if !ok {
			continue
		}
		v.Events = append(v.Events, EventView{
			ID: ev.ID, Type: string(ev.Type), Image: ev.ProcImage,
			Object: object(ev), Verb: verb(ev), TS: ev.TS,
		})
	}
	return v
}

func object(ev correlate.Event) string {
	switch ev.Type {
	case correlate.FileWrite, correlate.FileRead, correlate.ModuleLoad:
		return ev.FilePath
	case correlate.NetConnect:
		return fmt.Sprintf("%s:%d", ev.RemoteAddr, ev.RemotePort)
	case correlate.DNSQuery:
		return ev.DNSName
	}
	return ""
}

func verb(ev correlate.Event) string {
	if ev.Type == correlate.FileRead {
		return "read"
	}
	return "wrote"
}
