// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type connsnoopConnEvent struct {
	_      structs.HostLayout
	Pid    uint32
	_      [4]byte
	Ts     uint64
	Family uint16
	Dport  uint16
	Daddr  [4]uint8
	Daddr6 [16]uint8
	Comm   [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	connsnoopMapEvents          = "events"
	connsnoopProgHandleConn     = "handle_conn"
	connsnoopVarUnusedConnEvent = "unused_conn_event"
)

// loadConnsnoop returns the embedded CollectionSpec for connsnoop.
func loadConnsnoop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnsnoopBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load connsnoop: %w", err)
	}

	return spec, err
}

// loadConnsnoopObjects loads connsnoop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*connsnoopObjects
//	*connsnoopPrograms
//	*connsnoopMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConnsnoopObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadConnsnoop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// connsnoopSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connsnoopSpecs struct {
	connsnoopProgramSpecs
	connsnoopMapSpecs
	connsnoopVariableSpecs
}

// connsnoopProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connsnoopProgramSpecs struct {
	HandleConn *ebpf.ProgramSpec `ebpf:"handle_conn"`
}

// connsnoopMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connsnoopMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// connsnoopVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connsnoopVariableSpecs struct {
	UnusedConnEvent *ebpf.VariableSpec `ebpf:"unused_conn_event"`
}

// connsnoopObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConnsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type connsnoopObjects struct {
	connsnoopPrograms
	connsnoopMaps
	connsnoopVariables
}

func (o *connsnoopObjects) Close() error {
	return _ConnsnoopClose(
		&o.connsnoopPrograms,
		&o.connsnoopMaps,
	)
}

// connsnoopMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConnsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type connsnoopMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *connsnoopMaps) Close() error {
	return _ConnsnoopClose(
		m.Events,
	)
}

// connsnoopVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConnsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type connsnoopVariables struct {
	UnusedConnEvent *ebpf.Variable `ebpf:"unused_conn_event"`
}

// connsnoopPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConnsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type connsnoopPrograms struct {
	HandleConn *ebpf.Program `ebpf:"handle_conn"`
}

func (p *connsnoopPrograms) Close() error {
	return _ConnsnoopClose(
		p.HandleConn,
	)
}

func _ConnsnoopClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connsnoop_bpfeb.o
var _ConnsnoopBytes []byte
