// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type filesnoopFileEvent struct {
	_        structs.HostLayout
	Pid      uint32
	_        [4]byte
	Ts       uint64
	Start    uint64
	Flags    uint32
	IsWrite  uint8
	Comm     [16]uint8
	Filename [256]uint8
	_        [3]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	filesnoopMapEvents          = "events"
	filesnoopProgHandleOpenat   = "handle_openat"
	filesnoopVarUnusedFileEvent = "unused_file_event"
)

// loadFilesnoop returns the embedded CollectionSpec for filesnoop.
func loadFilesnoop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FilesnoopBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load filesnoop: %w", err)
	}

	return spec, err
}

// loadFilesnoopObjects loads filesnoop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*filesnoopObjects
//	*filesnoopPrograms
//	*filesnoopMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFilesnoopObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadFilesnoop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// filesnoopSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filesnoopSpecs struct {
	filesnoopProgramSpecs
	filesnoopMapSpecs
	filesnoopVariableSpecs
}

// filesnoopProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filesnoopProgramSpecs struct {
	HandleOpenat *ebpf.ProgramSpec `ebpf:"handle_openat"`
}

// filesnoopMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filesnoopMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// filesnoopVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filesnoopVariableSpecs struct {
	UnusedFileEvent *ebpf.VariableSpec `ebpf:"unused_file_event"`
}

// filesnoopObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFilesnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type filesnoopObjects struct {
	filesnoopPrograms
	filesnoopMaps
	filesnoopVariables
}

func (o *filesnoopObjects) Close() error {
	return _FilesnoopClose(
		&o.filesnoopPrograms,
		&o.filesnoopMaps,
	)
}

// filesnoopMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFilesnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type filesnoopMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *filesnoopMaps) Close() error {
	return _FilesnoopClose(
		m.Events,
	)
}

// filesnoopVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFilesnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type filesnoopVariables struct {
	UnusedFileEvent *ebpf.Variable `ebpf:"unused_file_event"`
}

// filesnoopPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFilesnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type filesnoopPrograms struct {
	HandleOpenat *ebpf.Program `ebpf:"handle_openat"`
}

func (p *filesnoopPrograms) Close() error {
	return _FilesnoopClose(
		p.HandleOpenat,
	)
}

func _FilesnoopClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filesnoop_bpfeb.o
var _FilesnoopBytes []byte
